CREATE OR REPLACE TRIGGER MHTRWO_ID_SEQ_TRG
BEFORE INSERT ON MHTRWO
FOR EACH ROW
  WHEN (new.ID IS NULL)
BEGIN
	:new.ID := mhtrwo_seq.nextval;
	DBMS_OUTPUT.PUT_LINE('Setting ID');
END;

CREATE OR REPLACE TRIGGER MHTRWO_ACCOUNT_ID_SEQ_TRG
BEFORE INSERT ON MHTRWO_ACCOUNT
FOR EACH ROW
  WHEN (new.ID IS NULL)
BEGIN
	:new.ID := mhtrwo_account_seq.nextval;
	DBMS_OUTPUT.PUT_LINE('Setting ID');
END;

CREATE OR REPLACE TRIGGER INSERT_MHTRWO_LOG
  BEFORE
    INSERT OR
    UPDATE OF ONOMA, EPONYMO, PATRONYMO, SALARY, AFM, HMNIA_GENHSHS OR
    DELETE
  ON MHTRWO
DECLARE
  TABLE_NAME VARCHAR(32);
BEGIN
  SELECT TABLE_NAME INTO TABLE_NAME FROM USER_TRIGGERS WHERE TRIGGER_NAME='INSERT_MHTRWO_LOG';
  CASE
    WHEN INSERTING THEN
      INSERT INTO MHTRWO_AUDIT_LOG VALUES(mhtrwo_audit_log_seq.nextval, 'Inserting', CURRENT_TIMESTAMP, TABLE_NAME);
      DBMS_OUTPUT.PUT_LINE('Inserting');
    WHEN UPDATING THEN
      INSERT INTO MHTRWO_AUDIT_LOG VALUES(mhtrwo_audit_log_seq.nextval, 'Updating', CURRENT_TIMESTAMP, TABLE_NAME);
      DBMS_OUTPUT.PUT_LINE('Updating');
    WHEN DELETING THEN
      INSERT INTO MHTRWO_AUDIT_LOG VALUES(mhtrwo_audit_log_seq.nextval, 'Deleting', CURRENT_TIMESTAMP, TABLE_NAME);
      DBMS_OUTPUT.PUT_LINE('Deleting');
  END CASE;
END;

CREATE OR REPLACE TRIGGER INSERT_MHTRWO_ACCOUNT_LOG
  BEFORE
    INSERT OR
    UPDATE OF MHTRWO_ID, BALANCE OR
    DELETE
  ON MHTRWO_ACCOUNT
DECLARE
  TABLE_NAME VARCHAR(32);
BEGIN
  SELECT TABLE_NAME INTO TABLE_NAME FROM USER_TRIGGERS WHERE TRIGGER_NAME='INSERT_MHTRWO_ACCOUNT_LOG';
  CASE
    WHEN INSERTING THEN
      INSERT INTO MHTRWO_AUDIT_LOG VALUES(mhtrwo_audit_log_seq.nextval, 'Inserting', CURRENT_TIMESTAMP, TABLE_NAME);
      DBMS_OUTPUT.PUT_LINE('Inserting');
    WHEN UPDATING THEN
      INSERT INTO MHTRWO_AUDIT_LOG VALUES(mhtrwo_audit_log_seq.nextval, 'Updating', CURRENT_TIMESTAMP, TABLE_NAME);
      DBMS_OUTPUT.PUT_LINE('Updating');
    WHEN DELETING THEN
      INSERT INTO MHTRWO_AUDIT_LOG VALUES(mhtrwo_audit_log_seq.nextval, 'Deleting', CURRENT_TIMESTAMP, TABLE_NAME);
      DBMS_OUTPUT.PUT_LINE('Deleting');
  END CASE;
END;
