CREATE TABLE "MHTRWO" (
	"ID" NUMBER(19,0) NOT NULL ENABLE,
	"ONOMA" VARCHAR2(128 CHAR),
	"EPONYMO" VARCHAR2(128 CHAR),
	"PATRONYMO" VARCHAR2(128),
    "AFM" NUMBER(19,0),
	"HMNIA" DATE,
    "SALARY" FLOAT(53),
	 CONSTRAINT "MHTRWO_PK" PRIMARY KEY ("ID"),
	 CONSTRAINT "MHTRWO_AFM_UNIQUE" UNIQUE ("AFM")
);

CREATE TABLE "MHTRWO_ACCOUNT" (
    "ID" NUMBER(19,0) NOT NULL ENABLE,
    "MHTRWO_ID" NUMBER(19,0) NOT NULL ENABLE,
    "IBAN" VARCHAR2(100),
    "BALANCE" FLOAT(126),
    CONSTRAINT "MHTRWO_ACCOUNT_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "MHTRWO_ACCOUNT_MHTRWO_FK" FOREIGN KEY ("MHTRWO_ID") REFERENCES "MHTRWO" ("ID")
);

CREATE TABLE "MHTRWO_AUDIT_LOG" (
    "ID" NUMBER(38,0),
	"MESSAGE" VARCHAR2(100),
	"TABLE_NAME" VARCHAR2(100),
	"TIMESTAMP" TIMESTAMP (6),
	CONSTRAINT "MHTRWO_AUDIT_LOG_PK" PRIMARY KEY ("ID")
);
