CREATE TABLE "MHTRWO" (
	"ID" NUMBER(19,0) NOT NULL ENABLE,
	"ONOMA" VARCHAR2(50),
	"EPONYMO" VARCHAR2(80),
	"PATRONYMO" VARCHAR2(50),
    "AFM" CHAR(9),
	"HMNIA_GENHSHS" DATE,
    "SALARY" FLOAT(53),
	 CONSTRAINT "MHTRWO_PK" PRIMARY KEY ("ID"),
	 CONSTRAINT "MHTRWO_AFM_UNIQUE" UNIQUE ("AFM"),
	 CONSTRAINT "MHTRWO_AFM_LENGTH_CHECK" CHECK (LENGTH(AFM) = 9)
);

CREATE TABLE "MHTRWO_ACCOUNT" (
    "ID" NUMBER(19,0) NOT NULL ENABLE,
    "MHTRWO_ID" NUMBER(19,0) NOT NULL ENABLE,
    "IBAN" VARCHAR2(34),
    "BALANCE" FLOAT(126),
    CONSTRAINT "MHTRWO_ACCOUNT_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "MHTRWO_ACCOUNT_MHTRWO_FK" FOREIGN KEY ("MHTRWO_ID") REFERENCES "MHTRWO" ("ID"),
    CONSTRAINT "MHTRWO_ACCOUNT_IBAN_UNIQUE" UNIQUE ("IBAN")
);

CREATE TABLE "MHTRWO_AUDIT_LOG" (
    "ID" NUMBER(38,0),
	"MESSAGE" VARCHAR2(100),
	"TABLE_NAME" VARCHAR2(100),
	"TIMESTAMP" TIMESTAMP (6),
	CONSTRAINT "MHTRWO_AUDIT_LOG_PK" PRIMARY KEY ("ID")
);
